import type { Adventure } from "./types";

/**
 * The TURA catalogue.
 *
 * Composition is deliberate and is asserted in `catalogue.test.ts`:
 *   - 48 of 64 (75%) sit inside the UK
 *   - 32 of 64 (50%) are two-night, adults-only, uninterrupted escapes
 *   - every entry is a real place with real coordinates
 *
 * Costs are all-in for two adults in GBP: fuel or flights, a bed or a pitch,
 * food, and whatever the activity itself costs.
 */
export const ADVENTURES: Adventure[] = [
  // ── Lake District ────────────────────────────────────────────────────────
  {
    id: "wasdale-head",
    ref: "TURA-001",
    title: "Wasdale Head & the deepest water in England",
    location: "Wasdale Head, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.4676, lng: -3.2761 },
    categories: ["mountains", "hiking", "wild-swimming", "camping"],
    nights: 2,
    adultsOnly: true,
    popularity: 94,
    estimatedCost: 310,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "England's highest ground above its deepest lake, at the end of a road that goes nowhere else. Two nights at the head of the valley, Scafell Pike on the full day, and the screes to swim beneath.",
    highlights: [
      "Scafell Pike by the Corridor Route rather than the tourist path from Wasdale",
      "Swimming off the shingle at the north-west end of Wast Water, 79m of black water below",
      "The Wasdale Head Inn — the only building for miles that sells beer",
      "No phone signal in the valley, which is the entire point",
    ],
    kit: [
      "Map and compass — cloud drops onto Scafell fast",
      "Tow float and neoprene socks for the screes",
      "Head torch each for the walk back from the inn",
    ],
  },
  {
    id: "buttermere-round",
    ref: "TURA-002",
    title: "Buttermere and the Haystacks round",
    location: "Buttermere, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.5397, lng: -3.2769 },
    categories: ["lakes", "wild-swimming", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 88,
    estimatedCost: 290,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "The most photographed four miles in the Lakes, and still worth it at seven in the morning when nobody else is up. Haystacks on day two, Innominate Tarn for lunch.",
    highlights: [
      "The flat lakeside circuit before breakfast, with the pines at Crummock end to yourselves",
      "Haystacks — Wainwright's favourite, and he had opinions",
      "Swimming at Innominate Tarn, 500m up with the whole of Gable opposite",
      "Scale Force, the tallest single drop in the Lake District",
    ],
    kit: [
      "Swim kit packed at the top of the bag, not the bottom",
      "Cash for the honesty box at the Syke Farm ice cream shed",
    ],
  },
  {
    id: "coniston-paddle",
    ref: "TURA-003",
    title: "Coniston Water end to end by kayak",
    location: "Coniston, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.3453, lng: -3.0714 },
    categories: ["kayaking", "lakes", "camping"],
    nights: 2,
    adultsOnly: true,
    popularity: 81,
    estimatedCost: 340,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "Five miles of open water with the Old Man above you the whole way. Launch at the north end, paddle to Peel Island and back over two unhurried days.",
    highlights: [
      "Peel Island — Arthur Ransome's Wild Cat Island, and you can land on it",
      "The Coniston launch permit is a few pounds and covers the whole lake",
      "Steam yacht Gondola passing you at close range, which never stops being odd",
      "Sunset from the east shore, with the Old Man going pink",
    ],
    kit: [
      "Buoyancy aids — non-negotiable, and the lake is cold all year",
      "Dry bag for phones and the car key",
      "Coniston launch permit, bought online before you set off",
    ],
  },
  {
    id: "great-langdale",
    ref: "TURA-004",
    title: "Great Langdale under the Pikes",
    location: "Great Langdale, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.4478, lng: -3.0961 },
    categories: ["camping", "mountains", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 86,
    estimatedCost: 280,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "Camp on the valley floor with the Langdale Pikes filling the windscreen, then take the Crinkle Crags and Bowfell horseshoe on the full day.",
    highlights: [
      "The Crinkles horseshoe — the Bad Step is optional and there is a way round",
      "Dungeon Ghyll Force, a short scramble from the campsite",
      "The Old Dungeon Ghyll hikers' bar, unchanged in decades",
      "Stickle Tarn under Pavey Ark at first light",
    ],
    kit: [
      "Proper pegs — the Langdale valley floor is thin soil over rock",
      "Waterproof trousers, not just a jacket",
    ],
  },
  {
    id: "ullswater-sail",
    ref: "TURA-005",
    title: "Ullswater by sail and the Ullswater Way",
    location: "Glenridding, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.5453, lng: -2.9497 },
    categories: ["sailing", "lakes", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 79,
    estimatedCost: 395,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "A dinghy day out of Glenridding on the second-largest lake in the Lakes, then the Howtown-to-Patterdale shoreline path back — widely reckoned the finest low-level walk in England.",
    highlights: [
      "Ullswater steamers one way, walk the other — the classic arrangement",
      "The shoreline path under Place Fell, which never leaves the water",
      "Aira Force from the bottom, not the car park",
      "Sailing club hire at Glenridding, tuition included if you need it",
    ],
    kit: [
      "Sailing gloves and a spare fleece — the wind funnels hard down the lake",
      "Boots for the walk, which is longer than it looks on the map",
    ],
  },
  {
    id: "ennerdale-wild",
    ref: "TURA-006",
    title: "Ennerdale — the valley they let go wild",
    location: "Ennerdale Bridge, Cumbria",
    region: "Lake District",
    country: "England",
    uk: true,
    coords: { lat: 54.5219, lng: -3.3736 },
    categories: ["forest", "bushcraft", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 68,
    estimatedCost: 265,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "Britain's most ambitious rewilding valley, with no through road and the River Liza left to move where it likes. Two nights of woodcraft, fire and genuinely dark skies.",
    highlights: [
      "The Liza braiding across its own floodplain — almost unique in England",
      "Black Sail Hut at the head of the valley, the remotest hostel in the country",
      "Regenerating Scots pine and juniper, planted by nobody",
      "Fire-lighting and a brew with no light pollution in any direction",
    ],
    kit: [
      "Firesteel and a folding saw for deadfall only",
      "Water filter — the Liza is clean but it is still a river",
      "Bivvy or small tent; there are no facilities past Bowness Knott",
    ],
  },
  // ── Eryri / Snowdonia ────────────────────────────────────────────────────
  {
    id: "llyn-gwynant",
    ref: "TURA-007",
    title: "Llyn Gwynant, camp and swim",
    location: "Nant Gwynant, Gwynedd",
    region: "Eryri (Snowdonia)",
    country: "Wales",
    uk: true,
    coords: { lat: 53.0369, lng: -4.0247 },
    categories: ["camping", "wild-swimming", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 91,
    estimatedCost: 295,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 4,
    summary:
      "Pitch on the grass that runs straight into the lake, with Yr Wyddfa's whole south side above you. Swim before breakfast, take the Watkin Path after it.",
    highlights: [
      "Swimming out to the small island in the middle of Llyn Gwynant",
      "The Watkin Path from the campsite gate — the finest way up Yr Wyddfa",
      "Gwynant's own rope swing, which is older than either of you",
      "Sunset light on Yr Aran, straight up the valley",
    ],
    kit: [
      "Book the lakeside pitches specifically — the field behind is a different trip",
      "Wetsuit if you are going in before May",
    ],
  },
  {
    id: "ogwen-tryfan",
    ref: "TURA-008",
    title: "Tryfan north ridge and the Ogwen valley",
    location: "Ogwen, Conwy",
    region: "Eryri (Snowdonia)",
    country: "Wales",
    uk: true,
    coords: { lat: 53.1189, lng: -3.9967 },
    categories: ["mountains", "hiking"],
    nights: 1,
    adultsOnly: false,
    popularity: 84,
    estimatedCost: 155,
    difficulty: "serious",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "amber",
    travelHours: 4,
    summary:
      "The best grade-1 scramble in Wales, straight off the A5. A mountain you cannot walk up — every route to the top of Tryfan needs hands.",
    highlights: [
      "The north ridge — 600m of continuous scrambling, no rope needed in dry weather",
      "Adam and Eve, the two blocks on the summit, and the jump between them",
      "Llyn Idwal and the Devil's Kitchen on the way back",
      "One night at Gwern Gof Uchaf, the campsite directly beneath the ridge",
    ],
    kit: [
      "Sticky-soled approach shoes rather than stiff boots",
      "Helmet if there is anyone above you",
      "Do not attempt in the wet — the rhyolite turns to glass",
    ],
  },
  {
    id: "cadair-idris",
    ref: "TURA-009",
    title: "Cadair Idris and the Mawddach estuary",
    location: "Dolgellau, Gwynedd",
    region: "Eryri (Snowdonia)",
    country: "Wales",
    uk: true,
    coords: { lat: 52.6997, lng: -3.9111 },
    categories: ["mountains", "hiking", "coast"],
    nights: 2,
    adultsOnly: true,
    popularity: 76,
    estimatedCost: 285,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 3.5,
    summary:
      "The Pony Path up, the Minffordd Path down, and a whole second day on the Mawddach trail where the mountain runs into the sea.",
    highlights: [
      "Llyn Cau in its cirque — the single best view of a lake in Wales",
      "The legend that a night on the summit leaves you a poet or a madman",
      "The Mawddach trail along the old railway, flat and nine miles of estuary",
      "Barmouth bridge at high tide with the mountain behind",
    ],
    kit: [
      "Full waterproofs — Cadair makes its own weather off the sea",
      "Bike hire on the Mawddach if you would rather ride the second day",
    ],
  },
  {
    id: "llyn-peninsula",
    ref: "TURA-010",
    title: "Llŷn Peninsula and the pub on the beach",
    location: "Porthdinllaen, Gwynedd",
    region: "Llŷn Peninsula",
    country: "Wales",
    uk: true,
    coords: { lat: 52.9425, lng: -4.5678 },
    categories: ["coast", "sailing", "wild-swimming"],
    nights: 2,
    adultsOnly: true,
    popularity: 74,
    estimatedCost: 330,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "A peninsula that feels like an island, with the Ty Coch Inn sat directly on the sand at Porthdinllaen and no road to it.",
    highlights: [
      "Walking in across the golf links — there is genuinely no other way",
      "Whistling Sands at Porthor, which squeaks underfoot",
      "Bardsey Sound and the view to Ynys Enlli",
      "Mynydd Mawr at the very tip, for the sunset over the island",
    ],
    kit: [
      "Cash for the Ty Coch — signal and card machines are both unreliable",
      "Tide times, if you want the sand rather than the shingle",
    ],
  },
  {
    id: "coed-y-brenin",
    ref: "TURA-011",
    title: "Coed y Brenin, a night in the king's forest",
    location: "Ganllwyd, Gwynedd",
    region: "Eryri (Snowdonia)",
    country: "Wales",
    uk: true,
    coords: { lat: 52.8267, lng: -3.8836 },
    categories: ["forest", "bushcraft", "wild-swimming"],
    nights: 1,
    adultsOnly: false,
    popularity: 63,
    estimatedCost: 140,
    difficulty: "gentle",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "amber",
    travelHours: 4,
    summary:
      "Nine thousand acres of Douglas fir and oak over three river gorges. One night, a fire, and the waterfalls of the Afon Mawddach to yourselves.",
    highlights: [
      "Pistyll Cain and Rhaeadr Mawddach, two falls within a few hundred metres",
      "The old gold mine workings at Gwynfynydd in the trees",
      "Plunge pools below the falls, deep enough to swim in properly",
      "Woodland that holds the damp — moss on everything, all year",
    ],
    kit: [
      "Midge net between June and September, seriously",
      "Dry firewood carried in; everything on the forest floor is wet",
    ],
  },
  // ── Pembrokeshire & west Wales ───────────────────────────────────────────
  {
    id: "stackpole-barafundle",
    ref: "TURA-012",
    title: "Barafundle and the Stackpole lily ponds",
    location: "Stackpole, Pembrokeshire",
    region: "Pembrokeshire Coast",
    country: "Wales",
    uk: true,
    coords: { lat: 51.6222, lng: -4.8919 },
    categories: ["coast", "wild-swimming", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 89,
    estimatedCost: 320,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 4.5,
    summary:
      "A beach with no road to it, reached over a headland and down a flight of steps. Two nights on the Pembrokeshire coast path with the lily ponds inland for the second day.",
    highlights: [
      "Barafundle Bay — half a mile from the nearest car park, which keeps it empty",
      "Broad Haven South and Church Rock at low tide",
      "The Bosherston lily ponds in June, when the whole surface is white",
      "Stackpole Quay to Freshwater East on the coast path, cliffs the whole way",
    ],
    kit: [
      "Swim shoes — the Barafundle steps are hot sand then sharp rock",
      "Everything carried in; there are no facilities on the beach at all",
    ],
  },
  {
    id: "st-davids-head",
    ref: "TURA-013",
    title: "St Davids Head and the Ramsey Sound paddle",
    location: "St Davids, Pembrokeshire",
    region: "Pembrokeshire Coast",
    country: "Wales",
    uk: true,
    coords: { lat: 51.8944, lng: -5.2831 },
    categories: ["coast", "kayaking", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 80,
    estimatedCost: 375,
    difficulty: "demanding",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 5,
    summary:
      "Britain's smallest city, a headland of Iron Age field walls, and a tidal sound with some of the fastest water in Wales to paddle when it slackens.",
    highlights: [
      "Coetan Arthur burial chamber on the headland, 5,000 years old and unfenced",
      "Ramsey Sound at slack water, with seals surfacing beside the boat",
      "Whitesands Bay for the evening swim",
      "The Bitches — a tidal race you look at rather than paddle",
    ],
    kit: [
      "Go with a guided outfit for the Sound unless you hold a sea kayak award",
      "Tide tables, and a plan built around slack water not daylight",
    ],
  },
  {
    id: "skomer-crossing",
    ref: "TURA-014",
    title: "Skomer Island in puffin season",
    location: "Martin's Haven, Pembrokeshire",
    region: "Pembrokeshire Coast",
    country: "Wales",
    uk: true,
    coords: { lat: 51.7353, lng: -5.2447 },
    categories: ["coast", "sailing"],
    nights: 0,
    adultsOnly: false,
    popularity: 72,
    estimatedCost: 95,
    difficulty: "gentle",
    bestSeasons: ["spring", "summer"],
    tier: "amber",
    travelHours: 5,
    summary:
      "A day boat across Jack Sound to an island with a quarter of a million seabirds on it, and puffins that walk past your boots without looking up.",
    highlights: [
      "Puffins ashore from April to late July, at arm's length on the Wick",
      "The largest Manx shearwater colony on earth, half a million pairs",
      "Iron Age hut circles and field systems visible across the whole island",
      "Jack Sound on the crossing, which is genuinely lively",
    ],
    kit: [
      "Landing tickets sell out — book the moment they release",
      "No shop, no cafe, no shelter: carry all food and water",
    ],
  },
  // ── Bannau Brycheiniog ───────────────────────────────────────────────────
  {
    id: "pen-y-fan-horseshoe",
    ref: "TURA-015",
    title: "The Pen y Fan horseshoe, before dawn",
    location: "Brecon, Powys",
    region: "Bannau Brycheiniog",
    country: "Wales",
    uk: true,
    coords: { lat: 51.8842, lng: -3.4361 },
    categories: ["mountains", "hiking"],
    nights: 1,
    adultsOnly: false,
    popularity: 82,
    estimatedCost: 145,
    difficulty: "moderate",
    bestSeasons: ["autumn", "winter", "spring"],
    tier: "amber",
    travelHours: 3,
    summary:
      "Start in the dark from Cwm Gwdi and take Cribyn, Pen y Fan and Corn Du as the light comes up, with the whole ridge to yourselves before the Storey Arms crowd arrives.",
    highlights: [
      "Cribyn's north ridge — steeper and emptier than anything on the tourist path",
      "Sunrise from Corn Du with cloud inversion filling the Usk valley",
      "Llyn Cwm Llwch in its hollow beneath the summit",
      "Down by the Gap Road, an old Roman route",
    ],
    kit: [
      "Head torches with fresh batteries — the start is properly dark",
      "Winter is the best season here, which means microspikes",
    ],
  },
  {
    id: "llyn-y-fan-fach",
    ref: "TURA-016",
    title: "Llyn y Fan Fach and the Black Mountain",
    location: "Llanddeusant, Carmarthenshire",
    region: "Bannau Brycheiniog",
    country: "Wales",
    uk: true,
    coords: { lat: 51.8836, lng: -3.7331 },
    categories: ["lakes", "wild-swimming", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 77,
    estimatedCost: 260,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 3.5,
    summary:
      "The emptiest quarter of the national park, a glacial lake under a 200m escarpment, and the legend of the lady of the lake that goes with it.",
    highlights: [
      "The escarpment ridge from Picws Du to Fan Brycheiniog, sheer on one side",
      "Swimming in Llyn y Fan Fach with the cliff directly above",
      "Llyn y Fan Fawr, the larger and far quieter twin over the ridge",
      "Dark sky reserve — the Milky Way is visible with the naked eye",
    ],
    kit: [
      "Navigation for the plateau, which is featureless in cloud",
      "The lake is 500m up and stays cold — neoprene from October",
    ],
  },
  {
    id: "waterfall-country",
    ref: "TURA-017",
    title: "Waterfall country and the walk behind the falls",
    location: "Ystradfellte, Powys",
    region: "Bannau Brycheiniog",
    country: "Wales",
    uk: true,
    coords: { lat: 51.7817, lng: -3.5658 },
    categories: ["forest", "wild-swimming", "hiking"],
    nights: 0,
    adultsOnly: false,
    popularity: 70,
    estimatedCost: 65,
    difficulty: "moderate",
    bestSeasons: ["spring", "autumn"],
    tier: "amber",
    travelHours: 3,
    summary:
      "Four waterfalls in four miles of wooded gorge, one of which you can walk right behind. Best in spring when the river is loud and the wild garlic is up.",
    highlights: [
      "Sgwd yr Eira — the path goes behind the curtain of water",
      "Sgwd y Pannwr and the two Clun-gwyn falls on the same circuit",
      "Plunge pools deep enough to swim between the falls",
      "Wild garlic through the whole gorge in April and May",
    ],
    kit: [
      "Grippy footwear — the gorge path is wet limestone and roots throughout",
      "A dry bag; you will get soaked behind Sgwd yr Eira whatever you do",
    ],
  },
  // ── Scotland ─────────────────────────────────────────────────────────────
  {
    id: "glen-coe",
    ref: "TURA-018",
    title: "Glen Coe and the Aonach Eagach",
    location: "Glencoe, Highland",
    region: "Highlands",
    country: "Scotland",
    uk: true,
    coords: { lat: 56.6667, lng: -5.0 },
    categories: ["mountains", "hiking", "camping"],
    nights: 2,
    adultsOnly: true,
    popularity: 96,
    estimatedCost: 420,
    difficulty: "serious",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 7,
    summary:
      "The most dramatic glen in Britain, entered over Rannoch Moor with the Buachaille standing in the road. Two nights, one big ridge, and light that changes every ten minutes.",
    highlights: [
      "Aonach Eagach — the narrowest mainland ridge in Britain, no escape once committed",
      "The Lost Valley, hidden between the Three Sisters, where the MacDonalds hid cattle",
      "Buachaille Etive Mòr from the Kingshouse at first light",
      "The Clachaig Inn, which still has a sign about the Campbells",
    ],
    kit: [
      "A head for heights on the Aonach Eagach — there is no way off the middle",
      "Midge repellent from June; Glen Coe is one of the worst places in Scotland",
      "Full winter kit if there is any snow on the tops",
    ],
  },
  {
    id: "skye-glen-brittle",
    ref: "TURA-019",
    title: "Glen Brittle, the Fairy Pools and the Cuillin",
    location: "Glenbrittle, Isle of Skye",
    region: "Isle of Skye",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.2, lng: -6.2833 },
    categories: ["wild-swimming", "mountains", "camping"],
    nights: 2,
    adultsOnly: true,
    popularity: 93,
    estimatedCost: 480,
    difficulty: "demanding",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "Camp on the beach at the foot of the Black Cuillin, swim the Fairy Pools before the coaches arrive, and take Coire Lagan on the day between.",
    highlights: [
      "The Fairy Pools at seven in the morning, empty and freezing",
      "Coire Lagan — a hanging corrie ringed by the whole Cuillin ridge",
      "The Glenbrittle campsite, pitched directly on the sand",
      "Gabbro so grippy you can walk up slabs that look impossible",
    ],
    kit: [
      "The Cuillin are magnetic — a compass will lie to you on the ridge",
      "Neoprene for the pools, which sit around 8°C in August",
      "Book Glenbrittle months ahead; it is small and it fills",
    ],
  },
  {
    id: "torridon-loch-maree",
    ref: "TURA-020",
    title: "Torridon and Loch Maree by canoe",
    location: "Kinlochewe, Highland",
    region: "Wester Ross",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.6833, lng: -5.4667 },
    categories: ["kayaking", "lakes", "forest", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 78,
    estimatedCost: 520,
    difficulty: "demanding",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 9.5,
    summary:
      "Paddle a loch with sixty wooded islands, under mountains that are older than almost anything else on the planet. Slioch on one side, Beinn Eighe on the other.",
    highlights: [
      "The island pinewoods on Loch Maree — untouched Caledonian forest, no deer, no grazing",
      "Slioch rising 980m straight out of the water",
      "Beinn Eighe, Britain's first national nature reserve",
      "Black-throated divers, which you will hear before you see",
    ],
    kit: [
      "Open canoe rather than kayak — the islands need landing on",
      "Loch Maree is big water; check the forecast and stay on the south shore in wind",
    ],
  },
  {
    id: "knoydart",
    ref: "TURA-021",
    title: "Knoydart, the last wilderness",
    location: "Inverie, Highland",
    region: "Knoydart",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.0331, lng: -5.6831 },
    categories: ["hiking", "bushcraft", "coast", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 85,
    estimatedCost: 560,
    difficulty: "serious",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "A peninsula with no road in. Boat from Mallaig or walk eighteen miles over the hills, then two nights in the community that lives at the end of it.",
    highlights: [
      "The Old Forge at Inverie — mainland Britain's remotest pub, community-owned",
      "Ladhar Bheinn, the most westerly Munro, straight out of the sea",
      "Barrisdale Bay at low tide, with nobody on it",
      "Getting there is the adventure — the ferry runs a few times a week",
    ],
    kit: [
      "Book the Mallaig ferry ahead; it is small and weather-dependent",
      "Everything you need for two days — the Inverie shop is tiny",
      "Tick removal tool, and check each other properly",
    ],
  },
  {
    id: "arran-lochranza",
    ref: "TURA-022",
    title: "Arran — Scotland in miniature",
    location: "Lochranza, Isle of Arran",
    region: "Isle of Arran",
    country: "Scotland",
    uk: true,
    coords: { lat: 55.7069, lng: -5.2969 },
    categories: ["coast", "hiking", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 75,
    estimatedCost: 430,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 7,
    summary:
      "An hour's ferry from Ardrossan puts you on an island with Highland peaks on one half and Lowland farmland on the other, split by a geological fault you can stand on.",
    highlights: [
      "Goatfell, 874m straight from sea level, with Ireland visible on a clear day",
      "Hutton's Unconformity at Lochranza — where modern geology was worked out",
      "Red deer wandering through Lochranza village at dusk, unbothered",
      "The Arran coastal way, and the standing stones on Machrie Moor",
    ],
    kit: [
      "Book the CalMac ferry with a car well ahead in summer",
      "Goatfell is granite and exposed — full waterproofs regardless of forecast",
    ],
  },
  {
    id: "loch-lomond-rowardennan",
    ref: "TURA-023",
    title: "Rowardennan, Ben Lomond and the loch",
    location: "Rowardennan, Stirling",
    region: "Loch Lomond & Trossachs",
    country: "Scotland",
    uk: true,
    coords: { lat: 56.1494, lng: -4.6414 },
    categories: ["lakes", "kayaking", "camping", "mountains"],
    nights: 1,
    adultsOnly: false,
    popularity: 73,
    estimatedCost: 175,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "amber",
    travelHours: 6,
    summary:
      "The most southerly Munro, straight up from the shore of the biggest lake in Britain by surface area, with a paddle on the loch to finish.",
    highlights: [
      "Ben Lomond by the tourist path up and the Ptarmigan ridge down",
      "The West Highland Way along the loch's east shore",
      "Paddling out to Inchlonaig or Inchconnachan on flat water",
      "The wooded east shore, which has no road on it at all",
    ],
    kit: [
      "Camping permits are required on the east shore March to September",
      "Buoyancy aids — Loch Lomond is deep and cold and gets choppy fast",
    ],
  },
  {
    id: "cairngorms-loch-avon",
    ref: "TURA-024",
    title: "Loch Avon basin, in the heart of the Cairngorms",
    location: "Cairn Gorm, Highland",
    region: "Cairngorms",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.0908, lng: -3.6478 },
    categories: ["mountains", "wild-swimming", "camping", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 83,
    estimatedCost: 445,
    difficulty: "serious",
    bestSeasons: ["summer"],
    tier: "green",
    travelHours: 8,
    summary:
      "The most remote-feeling place in Britain that is not an island: a loch at 730m ringed by cliffs on three sides, reached over the Cairngorm plateau.",
    highlights: [
      "The Shelter Stone — a howff under a fallen boulder, used for centuries",
      "Swimming in Loch Avon, which is around 6°C in August and utterly clear",
      "The plateau crossing from Cairn Gorm, arctic tundra with ptarmigan on it",
      "Cliffs of Carn Etchachan and Shelter Stone Crag rising straight from the water",
    ],
    kit: [
      "This is the sub-arctic — full winter kit outside July and August",
      "Navigation on the plateau in cloud is genuinely serious",
      "Tell someone your route; there is no signal in the basin",
    ],
  },
  {
    id: "assynt-suilven",
    ref: "TURA-025",
    title: "Suilven, out of the Assynt bog",
    location: "Lochinver, Highland",
    region: "Assynt",
    country: "Scotland",
    uk: true,
    coords: { lat: 58.1147, lng: -5.1381 },
    categories: ["mountains", "hiking", "camping"],
    nights: 2,
    adultsOnly: true,
    popularity: 87,
    estimatedCost: 550,
    difficulty: "serious",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 11,
    summary:
      "A sandstone whaleback standing alone out of a lochan-covered moor, with no other mountain touching it. Eleven miles round trip and every one of them worth it.",
    highlights: [
      "Suilven's profile — arguably the most recognisable mountain shape in Britain",
      "The Bealach Mòr, a saddle with 300m drops on both sides",
      "Assynt's lochan landscape, older than the Atlantic Ocean",
      "Lochinver, and the pie shop that everyone walking Suilven ends up at",
    ],
    kit: [
      "Boots you do not mind wrecking — the approach is six miles of bog",
      "Midge net, non-negotiable, June to September",
      "A full day's food; there is nothing between the car and the top",
    ],
  },
  {
    id: "harris-luskentyre",
    ref: "TURA-026",
    title: "Luskentyre and the Harris machair",
    location: "Luskentyre, Isle of Harris",
    region: "Outer Hebrides",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.8875, lng: -6.9694 },
    categories: ["coast", "wild-swimming", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 90,
    estimatedCost: 720,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 12,
    summary:
      "Three miles of white shell sand and turquoise water on the Atlantic edge of Europe, with the mountains of North Harris behind and almost nobody on it.",
    highlights: [
      "Luskentyre at low tide, when the sand goes out for half a mile",
      "The machair in June — wildflower grassland found almost nowhere else",
      "Seilebost across the sound, and the road between the two",
      "Swimming in genuinely Caribbean-coloured water at 12°C",
    ],
    kit: [
      "Ferry from Uig to Tarbert — book vehicle space months ahead",
      "Wind shell always; there is nothing between here and Newfoundland",
    ],
  },
  {
    id: "applecross",
    ref: "TURA-027",
    title: "Applecross over the Bealach na Bà",
    location: "Applecross, Highland",
    region: "Wester Ross",
    country: "Scotland",
    uk: true,
    coords: { lat: 57.4322, lng: -5.8156 },
    categories: ["coast", "camping", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 79,
    estimatedCost: 465,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 10,
    summary:
      "The steepest road in Britain climbs to 626m and drops you into a village facing Skye across the sound. Two nights of sunsets that go on for hours.",
    highlights: [
      "Bealach na Bà — hairpins, a 1-in-5 gradient, and no barriers",
      "The Applecross Inn, right on the shore, with langoustines landed that morning",
      "Sand Bay and the coast road north, which is emptier than the pass",
      "Sunset over Raasay and the Cuillin, from the beach at Applecross",
    ],
    kit: [
      "Do not take a caravan or a nervous driver over the Bealach",
      "Book the inn for dinner — it is the only kitchen for twenty miles",
    ],
  },
  {
    id: "jura-corryvreckan",
    ref: "TURA-028",
    title: "Jura and the Corryvreckan whirlpool",
    location: "Craighouse, Isle of Jura",
    region: "Inner Hebrides",
    country: "Scotland",
    uk: true,
    coords: { lat: 55.8333, lng: -5.9500 },
    categories: ["sailing", "coast", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 71,
    estimatedCost: 640,
    difficulty: "demanding",
    bestSeasons: ["summer"],
    tier: "red",
    travelHours: 9,
    summary:
      "An island with 200 people and 6,000 deer, the Paps standing over it, and the third-largest whirlpool in the world at its northern tip.",
    highlights: [
      "The Corryvreckan by RIB at spring tide, standing waves and a roar you hear from the shore",
      "The Paps of Jura, three quartzite cones with no path up any of them",
      "Barnhill, the house where Orwell wrote Nineteen Eighty-Four",
      "One road, one shop, one distillery, one hotel",
    ],
    kit: [
      "Book the Corryvreckan trip on a spring tide — neaps are a disappointment",
      "Two ferries to get here; plan the connection carefully",
    ],
  },
  {
    id: "rannoch-moor-bothy",
    ref: "TURA-029",
    title: "A bothy night on Rannoch Moor",
    location: "Rannoch Moor, Perth & Kinross",
    region: "Highlands",
    country: "Scotland",
    uk: true,
    coords: { lat: 56.6167, lng: -4.5833 },
    categories: ["bushcraft", "camping", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 69,
    estimatedCost: 335,
    difficulty: "serious",
    bestSeasons: ["spring", "autumn"],
    tier: "green",
    travelHours: 7.5,
    summary:
      "Fifty square miles of blanket bog, lochans and no roads. Walk in with fuel on your back, light the stove, and watch the dark arrive properly.",
    highlights: [
      "Mountain Bothies Association shelters — free, unlocked, no booking",
      "The moor at dusk, with red deer moving across it in hundreds",
      "Peat, granite and 10,000 years of undisturbed bog",
      "Corrour station on the West Highland Line, with no road to it either",
    ],
    kit: [
      "Carry coal or wood in; there is nothing burnable on a bog",
      "Bothy code: leave it cleaner than you found it, take all rubbish out",
      "Sleeping mat and bag rated properly — bothies are unheated stone",
    ],
  },
  {
    id: "loch-shiel",
    ref: "TURA-030",
    title: "Loch Shiel from Glenfinnan",
    location: "Glenfinnan, Highland",
    region: "Lochaber",
    country: "Scotland",
    uk: true,
    coords: { lat: 56.8722, lng: -5.4333 },
    categories: ["kayaking", "lakes", "forest"],
    nights: 2,
    adultsOnly: true,
    popularity: 76,
    estimatedCost: 460,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 9,
    summary:
      "Eighteen miles of freshwater fjord with a road at only one end. Paddle south from the monument and camp on a shore you can only reach by water.",
    highlights: [
      "The Glenfinnan viaduct and monument at the loch head",
      "Eilean Fhianain, the burial island, with a 13th-century chapel on it",
      "Oakwoods along the shore that have never been cleared",
      "A loch that gets emptier with every mile you paddle",
    ],
    kit: [
      "Full self-sufficiency below Polloch — no roads, no shops, no signal",
      "Weather window: Loch Shiel funnels wind and gets rough quickly",
    ],
  },
  // ── Northern England ─────────────────────────────────────────────────────
  {
    id: "embleton-bay",
    ref: "TURA-031",
    title: "Embleton Bay and Dunstanburgh",
    location: "Embleton, Northumberland",
    region: "Northumberland Coast",
    country: "England",
    uk: true,
    coords: { lat: 55.5069, lng: -1.6178 },
    categories: ["coast", "wild-swimming", "hiking"],
    nights: 1,
    adultsOnly: false,
    popularity: 78,
    estimatedCost: 165,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "amber",
    travelHours: 4.5,
    summary:
      "A mile of empty sand with a ruined castle on the headland at the end of it. Swim at dawn, walk to Craster for kippers, walk back.",
    highlights: [
      "Dunstanburgh Castle on its dolerite crag, reachable only on foot",
      "Embleton Bay at 6am — the whole beach, most mornings",
      "Craster smokehouse, doing kippers the same way since 1856",
      "Low Newton and the Ship Inn, which brews its own",
    ],
    kit: [
      "North Sea temperatures: 12–15°C at best, so a wetsuit unless you are hardened",
      "Wind shell — the Northumberland coast is exposed to everything",
    ],
  },
  {
    id: "kielder-dark-skies",
    ref: "TURA-032",
    title: "Kielder, under the darkest sky in England",
    location: "Kielder, Northumberland",
    region: "Northumberland",
    country: "England",
    uk: true,
    coords: { lat: 55.1889, lng: -2.5556 },
    categories: ["forest", "lakes", "camping", "kayaking"],
    nights: 2,
    adultsOnly: true,
    popularity: 74,
    estimatedCost: 300,
    difficulty: "gentle",
    bestSeasons: ["autumn", "winter"],
    tier: "green",
    travelHours: 5,
    summary:
      "The largest man-made forest and the largest man-made lake in northern Europe, inside the biggest area of protected dark sky in Europe. Come in October for the longest nights.",
    highlights: [
      "Kielder Observatory, booked ahead, with the Milky Way visible unaided outside",
      "The 26-mile lakeside way, walkable or rideable in a day",
      "Paddling the reservoir, which has 27 miles of shoreline",
      "Red squirrels — one of the last strongholds in England",
    ],
    kit: [
      "Observatory sessions are outdoors and cold; far more layers than you think",
      "Red-filter torches to keep your night vision",
    ],
  },
  {
    id: "farne-islands",
    ref: "TURA-033",
    title: "The Farne Islands and the seal colony",
    location: "Seahouses, Northumberland",
    region: "Northumberland Coast",
    country: "England",
    uk: true,
    coords: { lat: 55.6297, lng: -1.6603 },
    categories: ["sailing", "coast"],
    nights: 0,
    adultsOnly: false,
    popularity: 67,
    estimatedCost: 85,
    difficulty: "gentle",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "amber",
    travelHours: 4.5,
    summary:
      "A boat out of Seahouses to twenty-odd islands holding 100,000 seabirds and 6,000 grey seals, with a landing on Inner Farne in season.",
    highlights: [
      "Arctic terns dive-bombing you on the Inner Farne landing — bring a hat",
      "Puffins, guillemots, razorbills and kittiwakes at close range from the boat",
      "Grey seal pups on Longstone in November",
      "Grace Darling's lighthouse, and the story of the Forfarshire rescue",
    ],
    kit: [
      "A hat you do not mind being pecked, genuinely",
      "The crossing is short but lumpy — sea-sickness tablets an hour before",
    ],
  },
  {
    id: "malham-cove",
    ref: "TURA-034",
    title: "Malham Cove, Gordale and the limestone",
    location: "Malham, North Yorkshire",
    region: "Yorkshire Dales",
    country: "England",
    uk: true,
    coords: { lat: 54.0703, lng: -2.1508 },
    categories: ["hiking", "forest"],
    nights: 0,
    adultsOnly: false,
    popularity: 71,
    estimatedCost: 70,
    difficulty: "moderate",
    bestSeasons: ["spring", "autumn"],
    tier: "amber",
    travelHours: 3.5,
    summary:
      "An 80m limestone amphitheatre with a pavement on top, a gorge round the corner, and a tarn above. Eight miles takes in all three.",
    highlights: [
      "The limestone pavement on top of the Cove — clints, grikes, and a long drop",
      "Gordale Scar, where the path goes up the waterfall itself",
      "Janet's Foss, a tufa screen in the trees below Gordale",
      "Peregrines nesting on the Cove face, watched from the RSPB post in spring",
    ],
    kit: [
      "The pavement is lethal when wet — the grikes are ankle-breakers",
      "Gordale's scramble is a genuine grade 1; skip it in spate",
    ],
  },
  {
    id: "howgill-fells",
    ref: "TURA-035",
    title: "The Howgills, the fells everyone drives past",
    location: "Sedbergh, Cumbria",
    region: "Yorkshire Dales",
    country: "England",
    uk: true,
    coords: { lat: 54.3378, lng: -2.5350 },
    categories: ["hiking", "camping", "mountains"],
    nights: 2,
    adultsOnly: true,
    popularity: 64,
    estimatedCost: 245,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4,
    summary:
      "Smooth grassy whalebacks between the M6 and the Dales that almost nobody stops for. Two nights and you will have the whole massif to yourselves.",
    highlights: [
      "Cautley Spout — England's highest cascade above ground, 200m in stages",
      "The Calf and the ridge north, springy turf the entire way",
      "Wild fell ponies grazing the tops",
      "Sedbergh, England's book town, for the evening",
    ],
    kit: [
      "No paths on much of it — map and compass rather than a phone",
      "No water on the ridges; carry the day's supply up",
    ],
  },
  {
    id: "robin-hoods-bay",
    ref: "TURA-036",
    title: "Robin Hood's Bay and the Cleveland Way",
    location: "Robin Hood's Bay, North Yorkshire",
    region: "North York Moors",
    country: "England",
    uk: true,
    coords: { lat: 54.4342, lng: -0.5347 },
    categories: ["coast", "hiking", "wild-swimming"],
    nights: 2,
    adultsOnly: true,
    popularity: 72,
    estimatedCost: 275,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4,
    summary:
      "A smuggling village stacked down a ravine to the sea, a wave-cut scar full of fossils, and the best stretch of the Cleveland Way either side of it.",
    highlights: [
      "The scar at low tide — ammonites lying loose on the rock platform",
      "The clifftop path north to Whitby, past Saltwick Nab",
      "Boggle Hole, reachable along the beach if you get the tide right",
      "The village itself, where no car can reach the bottom",
    ],
    kit: [
      "Tide tables — the scar and the beach walk both cut off completely",
      "Fossils: collect loose, never hammer the cliff",
    ],
  },
  {
    id: "kinder-scout",
    ref: "TURA-037",
    title: "Kinder Scout and the trespass route",
    location: "Edale, Derbyshire",
    region: "Peak District",
    country: "England",
    uk: true,
    coords: { lat: 53.3861, lng: -1.8722 },
    categories: ["hiking", "mountains"],
    nights: 0,
    adultsOnly: false,
    popularity: 75,
    estimatedCost: 60,
    difficulty: "moderate",
    bestSeasons: ["autumn", "winter", "spring"],
    tier: "amber",
    travelHours: 2.5,
    summary:
      "The plateau that started the right to roam. Up Grindsbrook, across the peat hags to Kinder Downfall, and down Jacob's Ladder — the walk that everything else in the Peak is measured against.",
    highlights: [
      "Kinder Downfall blowing backwards in a westerly — the water goes up",
      "The 1932 mass trespass, which is why you can legally stand there",
      "Peat groughs and gritstone tors, a landscape found almost nowhere else",
      "Edale, and the start of the Pennine Way",
    ],
    kit: [
      "The plateau is featureless in cloud — compass, and know how to use it",
      "Gaiters; the groughs are black peat soup for most of the year",
    ],
  },
  {
    id: "dovedale",
    ref: "TURA-038",
    title: "Dovedale, the stepping stones and the dale",
    location: "Thorpe, Derbyshire",
    region: "Peak District",
    country: "England",
    uk: true,
    coords: { lat: 53.0533, lng: -1.7797 },
    categories: ["forest", "wild-swimming", "hiking"],
    nights: 0,
    adultsOnly: false,
    popularity: 66,
    estimatedCost: 55,
    difficulty: "gentle",
    bestSeasons: ["spring", "autumn"],
    tier: "amber",
    travelHours: 2.5,
    summary:
      "A limestone dale with ash woods on both sides, spires of rock standing out of them, and a clear river running through. Go early or go in November.",
    highlights: [
      "The stepping stones, which are the reason everyone else is there",
      "Ilam Rock and the Dove Holes, a mile upstream and far quieter",
      "Milldale and the packhorse bridge at the top of the dale",
      "Deep pools above Lover's Leap, cold and gin-clear",
    ],
    kit: [
      "Park at Ilam rather than the main car park and walk in the back way",
      "Water shoes for the river; the bed is sharp limestone",
    ],
  },
  // ── Southern England ─────────────────────────────────────────────────────
  {
    id: "dartmoor-wild-camp",
    ref: "TURA-039",
    title: "Dartmoor, the last legal wild camp in England",
    location: "Bellever, Devon",
    region: "Dartmoor",
    country: "England",
    uk: true,
    coords: { lat: 50.5658, lng: -3.9086 },
    categories: ["camping", "bushcraft", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 84,
    estimatedCost: 235,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 4,
    summary:
      "The only place in England where you can legally pitch a tent on open access land without asking. Two nights, granite tors, and a sky with nothing under it.",
    highlights: [
      "Backpack camping permitted on the commons — check the current map before you go",
      "Wistman's Wood, a stunted high-altitude oak wood full of moss and boulders",
      "The clapper bridge at Postbridge, medieval and still standing",
      "Letterboxing — a Dartmoor tradition since 1854",
    ],
    kit: [
      "Check the Dartmoor camping map and the firing range timetable before setting off",
      "No fires anywhere on the moor — stove only",
      "The ground holds water; a groundsheet and a bathtub floor matter",
    ],
  },
  {
    id: "wimbleball",
    ref: "TURA-040",
    title: "Wimbleball Lake and the Exmoor dark sky",
    location: "Brompton Regis, Somerset",
    region: "Exmoor",
    country: "England",
    uk: true,
    coords: { lat: 51.0475, lng: -3.4600 },
    categories: ["lakes", "kayaking", "camping"],
    nights: 1,
    adultsOnly: false,
    popularity: 61,
    estimatedCost: 150,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "amber",
    travelHours: 3.5,
    summary:
      "A 374-acre reservoir inside Europe's first International Dark Sky Reserve. Paddle in the afternoon, camp on the shore, and stay up for the sky.",
    highlights: [
      "Kayak and paddleboard hire on site, with the whole lake open",
      "Exmoor's dark sky reserve status — the Milky Way is unmissable",
      "The Exe valley and Tarr Steps, twenty minutes away",
      "Exmoor ponies on the open moor above the lake",
    ],
    kit: [
      "Warm layers for after dark; the reservoir sits at 300m and it drops",
      "Binoculars rather than a telescope for a first night out",
    ],
  },
  {
    id: "lizard-peninsula",
    ref: "TURA-041",
    title: "The Lizard, the most southerly point",
    location: "Lizard, Cornwall",
    region: "Cornwall",
    country: "England",
    uk: true,
    coords: { lat: 49.9594, lng: -5.2050 },
    categories: ["coast", "wild-swimming", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 82,
    estimatedCost: 385,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "green",
    travelHours: 5.5,
    summary:
      "Serpentine cliffs, a rock that only outcrops here and in a few places on earth, and the warmest sea in Britain. Two nights on the coast path either side of the point.",
    highlights: [
      "Kynance Cove at low tide, with serpentine stacks and white sand",
      "The Lizard Point itself, the southernmost land in Britain",
      "Cadgwith, a working cove with boats still hauled up the shingle",
      "Sea temperatures reaching 17–18°C in late August — the warmest in the UK",
    ],
    kit: [
      "Kynance is tidal — check times or the cove is underwater",
      "Coast path here is steep and eroded in places; proper footwear",
    ],
  },
  {
    id: "scilly-st-martins",
    ref: "TURA-042",
    title: "St Martin's, Isles of Scilly",
    location: "St Martin's, Isles of Scilly",
    region: "Isles of Scilly",
    country: "England",
    uk: true,
    coords: { lat: 49.9636, lng: -6.2864 },
    categories: ["coast", "sailing", "kayaking", "wild-swimming"],
    nights: 2,
    adultsOnly: true,
    popularity: 86,
    estimatedCost: 890,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 8,
    summary:
      "Twenty-eight miles off Land's End, on an island with 140 people, one shop and beaches that look imported. Swim with seals off the Eastern Isles.",
    highlights: [
      "Great Bay on the north coast, usually empty even in August",
      "Snorkelling with grey seals off the Eastern Isles, who come to you",
      "The vineyard and the island bakery, both of which are one-person operations",
      "Inter-island boats to Tresco's Abbey Gardens and uninhabited Samson",
    ],
    kit: [
      "Skybus from Land's End or the Scillonian ferry — both weather-dependent",
      "Book accommodation before booking travel; beds are the bottleneck",
    ],
  },
  {
    id: "durdle-door",
    ref: "TURA-043",
    title: "Lulworth to Durdle Door on the Jurassic Coast",
    location: "West Lulworth, Dorset",
    region: "Jurassic Coast",
    country: "England",
    uk: true,
    coords: { lat: 50.6214, lng: -2.2769 },
    categories: ["coast", "hiking", "wild-swimming"],
    nights: 0,
    adultsOnly: false,
    popularity: 77,
    estimatedCost: 75,
    difficulty: "moderate",
    bestSeasons: ["spring", "autumn"],
    tier: "amber",
    travelHours: 3,
    summary:
      "A limestone arch, a near-perfect circular cove, and 185 million years of coastline between them. Go out of season and go early.",
    highlights: [
      "Durdle Door from the beach at 7am, before the crowds come over the hill",
      "Lulworth Cove, a textbook example that is in every geography textbook",
      "Stair Hole and the Lulworth Crumple, folded rock you can walk up to",
      "The Fossil Forest, east of the cove, open when the ranges are not firing",
    ],
    kit: [
      "Check the Lulworth Ranges firing times for anything east of the cove",
      "The steps down to Durdle Door are steep and there are a lot of them",
    ],
  },
  {
    id: "new-forest",
    ref: "TURA-044",
    title: "A night in the New Forest",
    location: "Beaulieu, Hampshire",
    region: "New Forest",
    country: "England",
    uk: true,
    coords: { lat: 50.8156, lng: -1.4489 },
    categories: ["forest", "camping", "hiking"],
    nights: 1,
    adultsOnly: false,
    popularity: 62,
    estimatedCost: 135,
    difficulty: "gentle",
    bestSeasons: ["spring", "autumn"],
    tier: "amber",
    travelHours: 2.5,
    summary:
      "Ancient wood pasture that has been grazed continuously since William the Conqueror, with ponies, pigs and deer wandering through the campsite.",
    highlights: [
      "Camping directly in the open forest at Roundhill or Hollands Wood, no fences",
      "The Knightwood Oak, somewhere near 500 years old",
      "Pannage season in autumn, when pigs are turned out to eat the acorns",
      "Beaulieu River at high tide, and Buckler's Hard down the water",
    ],
    kit: [
      "Everything edible stowed — the ponies will get into a tent",
      "No open fires anywhere in the forest",
    ],
  },
  {
    id: "isle-of-wight",
    ref: "TURA-045",
    title: "Tennyson Down and the Needles",
    location: "Freshwater, Isle of Wight",
    region: "Isle of Wight",
    country: "England",
    uk: true,
    coords: { lat: 50.6633, lng: -1.5619 },
    categories: ["coast", "sailing", "hiking"],
    nights: 2,
    adultsOnly: true,
    popularity: 68,
    estimatedCost: 355,
    difficulty: "gentle",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "green",
    travelHours: 3,
    summary:
      "Chalk downland running out to three stacks in the sea, and a Solent full of sails behind you. Two nights, a ferry, and the best coastal walking in southern England.",
    highlights: [
      "Tennyson Down at dusk, 147m of chalk with sea on three sides",
      "The Needles and the old battery at the very end of the headland",
      "Alum Bay's coloured sand cliffs, which are genuinely that colour",
      "Yarmouth harbour, and a day's sailing on the Solent",
    ],
    kit: [
      "Book the car ferry ahead; walk-on is far cheaper if you can manage without",
      "The Down is completely exposed — a wind shell even in July",
    ],
  },
  {
    id: "norfolk-broads",
    ref: "TURA-046",
    title: "The Broads under sail at Hickling",
    location: "Hickling, Norfolk",
    region: "Norfolk Broads",
    country: "England",
    uk: true,
    coords: { lat: 52.7472, lng: 1.5789 },
    categories: ["sailing", "kayaking", "lakes"],
    nights: 2,
    adultsOnly: true,
    popularity: 65,
    estimatedCost: 340,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer"],
    tier: "green",
    travelHours: 3.5,
    summary:
      "Britain's largest protected wetland, all of it man-made by medieval peat digging. Take a traditional half-decker across Hickling Broad and moor where you like.",
    highlights: [
      "Hickling Broad, the largest of them, and shallow enough to see the bottom",
      "Marsh harriers and bitterns — the Broads hold most of the UK's population",
      "Horsey Mere and the seal colony on the beach beyond it",
      "Sailing a gaff-rigged half-decker, which is how it has always been done here",
    ],
    kit: [
      "Everything is shallow — a boat you can lift the plate on",
      "Insect repellent; it is a wetland in summer",
    ],
  },
  {
    id: "suffolk-shingle",
    ref: "TURA-047",
    title: "Shingle Street and the Ore estuary",
    location: "Shingle Street, Suffolk",
    region: "Suffolk Coast",
    country: "England",
    uk: true,
    coords: { lat: 52.0344, lng: 1.4478 },
    categories: ["coast", "kayaking", "wild-swimming"],
    nights: 1,
    adultsOnly: false,
    popularity: 58,
    estimatedCost: 145,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "amber",
    travelHours: 3,
    summary:
      "A row of coastguard cottages on an empty shingle spit, with a tidal river behind and Orford Ness across the water. One of the strangest, emptiest stretches of English coast.",
    highlights: [
      "The whelk shell line — a spiral of shells laid out by two people over years",
      "Orford Ness across the river: a former atomic weapons test site, now NT land",
      "Paddling the Ore and Alde on a rising tide",
      "No shop, no pub, no signal, and almost nobody",
    ],
    kit: [
      "The Ore runs fast — paddle with the tide, never against it",
      "Shingle is hard walking; carry less than you think you need",
    ],
  },
  {
    id: "wye-symonds-yat",
    ref: "TURA-048",
    title: "The Wye at Symonds Yat",
    location: "Symonds Yat, Herefordshire",
    region: "Wye Valley",
    country: "England",
    uk: true,
    coords: { lat: 51.8383, lng: -2.6428 },
    categories: ["kayaking", "forest", "wild-swimming"],
    nights: 0,
    adultsOnly: false,
    popularity: 69,
    estimatedCost: 90,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "amber",
    travelHours: 2.5,
    summary:
      "The Wye loops through a limestone gorge with peregrines on the crag above it. Canoe from Kerne Bridge down through the rapids to Symonds Yat, then walk back up to the rock.",
    highlights: [
      "Symonds Yat Rock, 120m above a river that goes right round beneath it",
      "The Yat rapids — grade 1–2, enough to be fun without being frightening",
      "Peregrine falcons on the Coldwell Rocks, watched from the RSPB viewpoint",
      "Ancient beech and yew woodland right down to the water",
    ],
    kit: [
      "Canoe hire includes shuttle back to the car — arrange it when you book",
      "Check river levels; the Wye is unrunnable in spate and boring when low",
    ],
  },
  // ── International (25%) ──────────────────────────────────────────────────
  {
    id: "lofoten",
    ref: "TURA-049",
    title: "Lofoten, where the Alps meet the Arctic sea",
    location: "Reine, Lofoten",
    region: "Nordland",
    country: "Norway",
    uk: false,
    coords: { lat: 67.9333, lng: 13.0889 },
    categories: ["coast", "hiking", "camping", "kayaking"],
    nights: 3,
    adultsOnly: true,
    popularity: 95,
    estimatedCost: 1250,
    difficulty: "demanding",
    bestSeasons: ["summer", "winter"],
    tier: "red",
    travelHours: 12,
    summary:
      "Granite peaks rising 1,000m directly out of the sea above white beaches, inside the Arctic Circle. Midnight sun in June, aurora from September.",
    highlights: [
      "Reinebringen — 1,566 steps built by Sherpas, and the view at the top",
      "Kvalvika beach, reached only on foot over a col",
      "Rorbuer — converted red fishermen's cabins on stilts over the water",
      "Right to roam: legal wild camping almost anywhere in Norway",
    ],
    kit: [
      "Fly to Bodø then ferry, or Evenes and drive — plan a full travel day each way",
      "Norway is expensive; carry food in from a supermarket, not the cabins",
    ],
  },
  {
    id: "chamonix",
    ref: "TURA-050",
    title: "Chamonix and the Mer de Glace",
    location: "Chamonix-Mont-Blanc",
    region: "Haute-Savoie",
    country: "France",
    uk: false,
    coords: { lat: 45.9237, lng: 6.8694 },
    categories: ["mountains", "hiking"],
    nights: 3,
    adultsOnly: true,
    popularity: 92,
    estimatedCost: 1180,
    difficulty: "demanding",
    bestSeasons: ["summer", "winter"],
    tier: "red",
    travelHours: 10,
    summary:
      "The birthplace of alpinism, under the highest mountain in western Europe. Three nights, the Aiguille du Midi cable car, and a stretch of the Tour du Mont Blanc.",
    highlights: [
      "Aiguille du Midi — 2,800m of vertical in twenty minutes, to 3,842m",
      "The Mer de Glace, and the ladders that measure how far it has retreated",
      "Lac Blanc on the Aiguilles Rouges side, with the whole Mont Blanc massif reflected",
      "The Grand Balcon Nord, a high traverse with no climbing involved",
    ],
    kit: [
      "Altitude at the Midi is real — go up slowly and do not linger if you feel it",
      "Multi-pass for the lifts pays for itself on day two",
    ],
  },
  {
    id: "dolomites-siusi",
    ref: "TURA-051",
    title: "Alpe di Siusi and the Sassolungo",
    location: "Alpe di Siusi, South Tyrol",
    region: "Dolomites",
    country: "Italy",
    uk: false,
    coords: { lat: 46.5397, lng: 11.6114 },
    categories: ["mountains", "hiking"],
    nights: 3,
    adultsOnly: true,
    popularity: 91,
    estimatedCost: 1120,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 11,
    summary:
      "Europe's largest high-altitude meadow at 1,800m, ringed by pale limestone towers that turn pink at sunset. Rifugio to rifugio, with a bed and a kitchen at every stop.",
    highlights: [
      "Enrosadira — the alpenglow that turns the whole range rose-red for ten minutes",
      "The rifugio system: hot food and a bunk at 2,500m, no tent needed",
      "Seceda's ridge, one of the most photographed skylines in the Alps",
      "Cars banned on the Alpe during the day, so it stays quiet",
    ],
    kit: [
      "Book rifugi in advance for July and August — they fill months ahead",
      "Via ferrata kit only if you intend to do one; most routes do not need it",
    ],
  },
  {
    id: "plitvice",
    ref: "TURA-052",
    title: "Plitvice Lakes and the travertine terraces",
    location: "Plitvička Jezera",
    region: "Lika-Senj",
    country: "Croatia",
    uk: false,
    coords: { lat: 44.8654, lng: 15.5820 },
    categories: ["lakes", "forest", "hiking"],
    nights: 3,
    adultsOnly: true,
    popularity: 80,
    estimatedCost: 950,
    difficulty: "gentle",
    bestSeasons: ["spring", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "Sixteen lakes falling into each other over natural dams that the water itself is still building. Beech and fir forest, ninety waterfalls, and boardwalks over all of it.",
    highlights: [
      "Travertine barriers still growing about a centimetre a year",
      "The Veliki Slap, 78m, at the bottom of the lower canyon",
      "Boardwalks running directly over clear water full of trout",
      "Go in October for autumn colour and a fraction of the crowds",
    ],
    kit: [
      "First entry of the day is the only way to have the boardwalks to yourselves",
      "Swimming is banned throughout the park — this is a looking trip",
    ],
  },
  {
    id: "stockholm-archipelago",
    ref: "TURA-053",
    title: "The Stockholm archipelago under sail",
    location: "Sandhamn, Stockholm",
    region: "Stockholm archipelago",
    country: "Sweden",
    uk: false,
    coords: { lat: 59.2864, lng: 18.9114 },
    categories: ["sailing", "kayaking", "coast", "camping"],
    nights: 3,
    adultsOnly: true,
    popularity: 76,
    estimatedCost: 1080,
    difficulty: "moderate",
    bestSeasons: ["summer"],
    tier: "red",
    travelHours: 6,
    summary:
      "Thirty thousand islands between Stockholm and the open Baltic. Sail or paddle out, and use allemansrätten to camp on whichever rock you like the look of.",
    highlights: [
      "Allemansrätten — the right to camp one night on any uncultivated land",
      "Sandhamn, the sailing capital, and the emptier outer islands beyond it",
      "Flat granite slabs warmed all day, perfect to swim off and sleep on",
      "Baltic water: barely salty, and 20°C in a good August",
    ],
    kit: [
      "Sea charts — the archipelago is a maze and GPS alone is not enough",
      "Everything carried in; the outer islands have nothing on them",
    ],
  },
  {
    id: "picos-de-europa",
    ref: "TURA-054",
    title: "Picos de Europa and the Cares Gorge",
    location: "Caín, Asturias",
    region: "Picos de Europa",
    country: "Spain",
    uk: false,
    coords: { lat: 43.1908, lng: -4.8283 },
    categories: ["mountains", "hiking"],
    nights: 3,
    adultsOnly: true,
    popularity: 79,
    estimatedCost: 890,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "red",
    travelHours: 8,
    summary:
      "Limestone peaks twenty miles from the Bay of Biscay, and a path cut into a gorge wall 200m above the river. Spain's first national park, and still its wildest.",
    highlights: [
      "The Cares Gorge — twelve kilometres of path blasted into a vertical wall",
      "The Fuente Dé cable car, 750m in four minutes",
      "Naranjo de Bulnes, a 500m limestone tower and the birthplace of Spanish climbing",
      "Cabrales cheese, made in caves in the mountains you are walking through",
    ],
    kit: [
      "The Cares is exposed with no barrier for most of its length",
      "Start the gorge from Poncebos and arrange transport back from Caín",
    ],
  },
  {
    id: "costa-vicentina",
    ref: "TURA-055",
    title: "Costa Vicentina and the Fishermen's Trail",
    location: "Odeceixe, Alentejo",
    region: "Costa Vicentina",
    country: "Portugal",
    uk: false,
    coords: { lat: 37.4364, lng: -8.7947 },
    categories: ["coast", "hiking", "wild-swimming"],
    nights: 3,
    adultsOnly: true,
    popularity: 81,
    estimatedCost: 830,
    difficulty: "moderate",
    bestSeasons: ["spring", "autumn"],
    tier: "red",
    travelHours: 7,
    summary:
      "The wildest coast in southern Europe: cliffs, storks nesting on sea stacks, and a walking trail on the paths fishermen still use to reach the rocks.",
    highlights: [
      "The Fishermen's Trail, on genuine clifftop paths rather than a made-up route",
      "White storks nesting on sea stacks — the only place in the world they do this",
      "Praia da Amoreira and Odeceixe, river beaches meeting the Atlantic",
      "Cabo de São Vicente, the south-western corner of the continent",
    ],
    kit: [
      "Sand walking is hard going — the trail is much slower than the distance suggests",
      "Atlantic swell here is serious; swim only where locals do",
    ],
  },
  {
    id: "dingle",
    ref: "TURA-056",
    title: "The Dingle Peninsula and the Blaskets",
    location: "Dingle, County Kerry",
    region: "Kerry",
    country: "Ireland",
    uk: false,
    coords: { lat: 52.1409, lng: -10.2686 },
    categories: ["coast", "kayaking", "hiking"],
    nights: 3,
    adultsOnly: true,
    popularity: 84,
    estimatedCost: 860,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "The most westerly land in Ireland, with beehive huts on the hillsides, an abandoned island offshore, and a peninsula road that keeps the Atlantic on your right the whole way.",
    highlights: [
      "Slea Head Drive, and the Blasket Islands sitting out in the swell",
      "Great Blasket — abandoned in 1953, landable by boat in summer",
      "Clochán beehive huts, dry-stone and over a thousand years old",
      "Sea kayaking out of Dingle harbour with the cliffs above you",
    ],
    kit: [
      "Ferry to Rosslare or fly to Kerry — the drive across Ireland is long",
      "Blasket landings are cancelled often; keep the day flexible",
    ],
  },
  {
    id: "connemara",
    ref: "TURA-057",
    title: "Connemara, the Twelve Bens and Killary",
    location: "Leenane, County Galway",
    region: "Connemara",
    country: "Ireland",
    uk: false,
    coords: { lat: 53.5989, lng: -9.6944 },
    categories: ["lakes", "hiking", "mountains", "kayaking"],
    nights: 3,
    adultsOnly: true,
    popularity: 74,
    estimatedCost: 790,
    difficulty: "demanding",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "Quartzite peaks over blanket bog and a fjord that cuts ten miles inland. The emptiest quarter of Ireland, and it feels it.",
    highlights: [
      "Killary Harbour, Ireland's only true glacial fjord",
      "The Twelve Bens — steep, pathless quartzite, and no easy days",
      "Kylemore Abbey on its lake, with the Bens behind",
      "Bog roads with nothing on them for miles in any direction",
    ],
    kit: [
      "Pathless and boggy — gaiters, and a map you can read in rain",
      "Connemara weather changes in minutes; carry full waterproofs always",
    ],
  },
  {
    id: "abisko",
    ref: "TURA-058",
    title: "Abisko, aurora and the Arctic winter",
    location: "Abisko, Norrbotten",
    region: "Swedish Lapland",
    country: "Sweden",
    uk: false,
    coords: { lat: 68.3489, lng: 18.8306 },
    categories: ["bushcraft", "camping", "mountains", "forest"],
    nights: 3,
    adultsOnly: true,
    popularity: 88,
    estimatedCost: 1400,
    difficulty: "serious",
    bestSeasons: ["winter"],
    tier: "red",
    travelHours: 13,
    summary:
      "Two hundred kilometres inside the Arctic Circle, in a rain shadow that gives it the clearest skies in Scandinavia. Snowshoes, a fire, and the aurora most clear nights from September to March.",
    highlights: [
      "The Aurora Sky Station on Mount Nuolja, reached by chairlift in the dark",
      "The Lapporten valley, a perfect U-shaped glacial notch",
      "Winter bushcraft — fire on snow, and a night in a heated lavvu",
      "Polar night in December: no sunrise at all for weeks",
    ],
    kit: [
      "Genuine expedition-weight kit; -25°C is a normal January night",
      "Camera on a tripod with manual settings — auto will not see the aurora",
      "Fly to Kiruna, then the train, which is part of the experience",
    ],
  },
  {
    id: "bohinj",
    ref: "TURA-059",
    title: "Lake Bohinj and the Julian Alps",
    location: "Bohinj, Upper Carniola",
    region: "Triglav National Park",
    country: "Slovenia",
    uk: false,
    coords: { lat: 46.2833, lng: 13.8833 },
    categories: ["lakes", "wild-swimming", "mountains", "kayaking"],
    nights: 3,
    adultsOnly: true,
    popularity: 83,
    estimatedCost: 870,
    difficulty: "moderate",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 8,
    summary:
      "Bled's bigger, quieter, wilder neighbour: a glacial lake inside Slovenia's only national park, with Triglav standing behind it and swimming allowed everywhere.",
    highlights: [
      "Swimming the length of Bohinj, which is warm enough by July",
      "The Savica waterfall, source of the Sava, up 500 steps",
      "Vogel cable car for the whole Julian Alps in one view",
      "The Soča valley over the pass — the most extraordinary river colour in Europe",
    ],
    kit: [
      "Bohinj is a national park lake — no motors, which is why it is quiet",
      "Vintgar and Savica both charge entry; carry euros in cash",
    ],
  },
  {
    id: "calanques-piana",
    ref: "TURA-060",
    title: "Calanques de Piana and the Scandola reserve",
    location: "Piana, Corse-du-Sud",
    region: "Corsica",
    country: "France",
    uk: false,
    coords: { lat: 42.2456, lng: 8.6353 },
    categories: ["coast", "sailing", "wild-swimming", "kayaking"],
    nights: 3,
    adultsOnly: true,
    popularity: 78,
    estimatedCost: 1020,
    difficulty: "moderate",
    bestSeasons: ["spring", "autumn"],
    tier: "red",
    travelHours: 8,
    summary:
      "Red granite towers dropping straight into a turquoise gulf, with a marine reserve next door that can only be reached by boat. Two UNESCO sites in one bay.",
    highlights: [
      "The Calanches de Piana at sunset, when the granite goes properly red",
      "Scandola nature reserve, accessible only from the water",
      "Girolata, a village with no road to it at all",
      "Snorkelling in water that is clear to twenty metres",
    ],
    kit: [
      "Boat trips to Scandola leave from Porto — book the small operators, not the big ones",
      "May or October; July in Corsica is hot and full",
    ],
  },
  {
    id: "thorsmork",
    ref: "TURA-061",
    title: "Þórsmörk, between three glaciers",
    location: "Þórsmörk, Suðurland",
    region: "South Iceland",
    country: "Iceland",
    uk: false,
    coords: { lat: 63.6817, lng: -19.4906 },
    categories: ["mountains", "hiking", "camping", "forest"],
    nights: 3,
    adultsOnly: true,
    popularity: 89,
    estimatedCost: 1320,
    difficulty: "serious",
    bestSeasons: ["summer"],
    tier: "red",
    travelHours: 7,
    summary:
      "A green valley enclosed by Eyjafjallajökull, Mýrdalsjökull and Tindfjallajökull, reached only by crossing unbridged glacial rivers in a highland bus.",
    highlights: [
      "The Fimmvörðuháls pass to Skógar, over ground created by the 2010 eruption",
      "Valahnúkur at midnight in June, with the sun still up",
      "Birch woodland in a country that has almost none left",
      "River crossings that make the journey in genuinely part of the trip",
    ],
    kit: [
      "Do not attempt the drive in a hire car — the crossings will write it off",
      "Highland bus from Reykjavík or Hvolsvöllur, booked ahead",
      "Weather can close the pass in July; always carry a full day's spare food",
    ],
  },
  {
    id: "sao-miguel",
    ref: "TURA-062",
    title: "São Miguel, crater lakes and hot springs",
    location: "Furnas, São Miguel",
    region: "Azores",
    country: "Portugal",
    uk: false,
    coords: { lat: 37.7719, lng: -25.3117 },
    categories: ["lakes", "wild-swimming", "hiking", "forest"],
    nights: 3,
    adultsOnly: true,
    popularity: 82,
    estimatedCost: 940,
    difficulty: "moderate",
    bestSeasons: ["spring", "summer", "autumn"],
    tier: "red",
    travelHours: 6,
    summary:
      "A volcanic island in the middle of the Atlantic with lakes in its craters, hot rivers running through the forest, and a four-hour flight from the UK.",
    highlights: [
      "Sete Cidades — twin crater lakes, one green and one blue, in the same caldera",
      "Poça da Dona Beija, thermal pools in the forest, open until eleven at night",
      "Caldeira Velha, a hot waterfall you can stand under",
      "Whale and dolphin watching — resident sperm whales year round",
    ],
    kit: [
      "Iron-rich thermal water permanently stains swimwear — take an old set",
      "Weather changes hourly; Sete Cidades is often in cloud by midday",
    ],
  },
  {
    id: "eibsee",
    ref: "TURA-063",
    title: "Eibsee, under the Zugspitze",
    location: "Grainau, Bavaria",
    region: "Bavarian Alps",
    country: "Germany",
    uk: false,
    coords: { lat: 47.4569, lng: 10.9769 },
    categories: ["lakes", "wild-swimming", "mountains", "kayaking"],
    nights: 3,
    adultsOnly: true,
    popularity: 75,
    estimatedCost: 900,
    difficulty: "gentle",
    bestSeasons: ["summer", "autumn"],
    tier: "red",
    travelHours: 9,
    summary:
      "A turquoise lake with eight wooded islands, sitting at 1,000m directly beneath Germany's highest mountain. Swim it in the morning, take the cable car in the afternoon.",
    highlights: [
      "Eibsee's colour — glacial flour in the water, and it really is that green",
      "The 7km shoreline path, with a different view of the Zugspitze at every turn",
      "Cable car to 2,962m, and the Austrian border across the summit",
      "Rowing boats and SUPs from the lakeside, no motors permitted",
    ],
    kit: [
      "Arrive before nine — the car park is small and fills by mid-morning",
      "Zugspitze summit is 15°C colder than the lake, whatever the season",
    ],
  },
  {
    id: "tatra-zakopane",
    ref: "TURA-064",
    title: "The High Tatras from Zakopane",
    location: "Zakopane, Lesser Poland",
    region: "Tatra Mountains",
    country: "Poland",
    uk: false,
    coords: { lat: 49.2992, lng: 19.9496 },
    categories: ["mountains", "hiking", "lakes"],
    nights: 3,
    adultsOnly: true,
    popularity: 73,
    estimatedCost: 720,
    difficulty: "demanding",
    bestSeasons: ["summer", "autumn", "winter"],
    tier: "red",
    travelHours: 7,
    summary:
      "The only genuinely alpine range in eastern Europe, packed into 300 square miles, with granite ridges, glacial lakes and chained scrambling routes above a mountain town.",
    highlights: [
      "Morskie Oko, a lake under a 1,000m wall, and the best-known view in Poland",
      "Orla Perć — the Eagle's Path, chained and exposed, one of Europe's hardest marked trails",
      "Rysy, the highest point in Poland, on the Slovak border",
      "Zakopane's wooden highlander architecture, and oscypek cheese off a grill",
    ],
    kit: [
      "Orla Perć is one-way in places and has a real fatality record — respect it",
      "Park entry is paid daily at the gate, in złoty",
    ],
  },
];

/** Quick lookup by id. */
export const ADVENTURE_BY_ID = new Map(ADVENTURES.map((a) => [a.id, a]));

export function getAdventure(id: string): Adventure | undefined {
  return ADVENTURE_BY_ID.get(id);
}
