/**
 * TURA domain model.
 *
 * Two adults, one shared plan. Everything here is persisted to LocalStorage
 * except the adventure catalogue itself, which ships with the app.
 */

/** Terrain / activity families the catalogue is built around. */
export const CATEGORIES = [
  "camping",
  "coast",
  "mountains",
  "forest",
  "lakes",
  "hiking",
  "kayaking",
  "sailing",
  "wild-swimming",
  "bushcraft",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_LABEL: Record<Category, string> = {
  camping: "Camping",
  coast: "Coast",
  mountains: "Mountains",
  forest: "Forest",
  lakes: "Lakes",
  hiking: "Hiking",
  kayaking: "Kayaking",
  sailing: "Sailing",
  "wild-swimming": "Wild swimming",
  bushcraft: "Bushcraft",
};

/** Budget tier — drives the calendar rhythm and the target spend. */
export const TIERS = ["green", "amber", "red"] as const;
export type Tier = (typeof TIERS)[number];

export const TIER_META: Record<
  Tier,
  { label: string; budget: number; cadence: string; description: string }
> = {
  green: {
    label: "Green",
    budget: 300,
    cadence: "Last Saturday, every month",
    description:
      "The monthly regular. Close enough to leave after work, cheap enough to never think twice.",
  },
  amber: {
    label: "Amber",
    budget: 200,
    cadence: "Mid-month Saturday, every other month",
    description:
      "The lean one. Wild camps, bothies and bring-your-own-everything nights.",
  },
  red: {
    label: "Red",
    budget: 1000,
    cadence: "Once a year, on the birthday",
    description:
      "The birthday adventure. One properly big trip a year, booked well ahead.",
  },
};

/** Where an adventure sits in the plan. */
export const STATUSES = [
  "idea",
  "shortlisted",
  "planned",
  "booked",
  "completed",
  "skipped",
] as const;
export type Status = (typeof STATUSES)[number];

export const STATUS_META: Record<
  Status,
  { label: string; description: string }
> = {
  idea: { label: "Idea", description: "In the catalogue, not yet chosen" },
  shortlisted: { label: "Shortlisted", description: "On the list for this year" },
  planned: { label: "Planned", description: "Dated, not yet paid for" },
  booked: { label: "Booked", description: "Paid for and locked in" },
  completed: { label: "Completed", description: "Done — and in the book" },
  skipped: { label: "Skipped", description: "Passed on this time" },
};

export type Difficulty = "gentle" | "moderate" | "demanding" | "serious";

export const DIFFICULTY_META: Record<
  Difficulty,
  { label: string; description: string }
> = {
  gentle: { label: "Gentle", description: "Easy going, no experience needed" },
  moderate: { label: "Moderate", description: "A decent day out, reasonable fitness" },
  demanding: { label: "Demanding", description: "Long days, real terrain, proper kit" },
  serious: { label: "Serious", description: "Skills, planning and a weather window" },
};

export type Season = "spring" | "summer" | "autumn" | "winter";

export interface Coordinates {
  lat: number;
  lng: number;
}

/**
 * A catalogue adventure. `ref` is the human-facing reference number shown in
 * calendar entries, the journal and the adventure book.
 */
export interface Adventure {
  id: string;
  /** e.g. "TURA-014" — stable, shown throughout the app. */
  ref: string;
  title: string;
  /** Nearest recognisable place, e.g. "Wasdale Head, Cumbria". */
  location: string;
  /** National park, coastline or range this belongs to. */
  region: string;
  country: string;
  /** true for the 75% of the catalogue that sits inside the UK. */
  uk: boolean;
  coords: Coordinates;
  categories: Category[];
  /** 0 = day trip, 1 = overnight, 2 = the two-night escape. */
  nights: number;
  /** Two adults only, no company, no interruptions. */
  adultsOnly: boolean;
  /** 1–100. Drives the "next 15 by popularity" ranking. */
  popularity: number;
  /** Realistic all-in cost for two adults, in GBP. */
  estimatedCost: number;
  difficulty: Difficulty;
  bestSeasons: Season[];
  /** Suggested tier, based on cost and how far away it is. */
  tier: Tier;
  /** Driving time from central England, in hours. */
  travelHours: number;
  summary: string;
  /** What actually makes this worth the drive. */
  highlights: string[];
  /** Adventure-specific kit, on top of the standard list. */
  kit: string[];
}

/** Per-adventure state the couple owns. */
export interface AdventureRecord {
  adventureId: string;
  status: Status;
  /** Checklist item ids that have been ticked. */
  checked: string[];
  notes: string;
  /** ISO date the couple marked it completed. */
  completedOn?: string;
  favourite: boolean;
  updatedAt: string;
}

/** A dated slot generated by the calendar rules, optionally filled. */
export interface CalendarSlot {
  /** Deterministic id, e.g. "green-2026-03". */
  id: string;
  /** ISO yyyy-mm-dd — always a Saturday. */
  date: string;
  tier: Tier;
  /** Target spend for the tier, in GBP. */
  budget: number;
  /** Assigned adventure, if the couple has picked one. */
  adventureId?: string;
  /** Overrides the tier budget when the couple sets their own number. */
  budgetOverride?: number;
  note?: string;
}

export type ExpenseCategory =
  | "travel"
  | "stay"
  | "food"
  | "kit"
  | "activity"
  | "other";

export const EXPENSE_CATEGORIES: ExpenseCategory[] = [
  "travel",
  "stay",
  "food",
  "kit",
  "activity",
  "other",
];

export const EXPENSE_LABEL: Record<ExpenseCategory, string> = {
  travel: "Travel",
  stay: "Stay",
  food: "Food & drink",
  kit: "Kit",
  activity: "Activity",
  other: "Other",
};

export interface Expense {
  id: string;
  slotId: string;
  adventureId?: string;
  label: string;
  amount: number;
  category: ExpenseCategory;
  date: string;
  createdAt: string;
}

export interface JournalEntry {
  id: string;
  adventureId: string;
  slotId?: string;
  /** ISO date the adventure happened. */
  date: string;
  title: string;
  body: string;
  /** 1–5. */
  rating: number;
  /** Free-text conditions, e.g. "Horizontal rain, then a clear dusk". */
  weather: string;
  /** Data URLs, downscaled on import to stay inside the storage budget. */
  photos: string[];
  /** Short quotable line pulled out for the adventure book. */
  standout: string;
  createdAt: string;
}

export interface Settings {
  /** Names of the two adults, used through the app. */
  partnerOne: string;
  partnerTwo: string;
  /** ISO yyyy-mm-dd. Drives the red birthday adventure each year. */
  birthday: string;
  /** Home point — distances and travel estimates are measured from here. */
  home: Coordinates;
  homeLabel: string;
  /** Which month the amber (every-other-month) rhythm starts on: 0 = Jan. */
  amberAnchorMonth: number;
  currency: string;
  theme: "dark" | "light" | "system";
  mapStyle: MapStyleId;
  onboarded: boolean;
}

export type MapStyleId = "terrain" | "satellite" | "outdoors";

/** The whole persisted state, versioned so migrations stay possible. */
export interface TuraState {
  version: number;
  settings: Settings;
  records: Record<string, AdventureRecord>;
  slots: Record<string, CalendarSlot>;
  expenses: Expense[];
  journal: JournalEntry[];
  /** Roulette results, newest first — keeps the wheel honest. */
  spins: { adventureId: string; at: string }[];
}
